### ISSUE TITLE
Redirect url doesn't work in subdirectory

### ISSUE THREAD

**Issue by gunner1095** [cakephp/authentication#352] opened 2020-02-22 23:13 UTC
I have a new installation of CakePHP 4 in localhost/v3. I created a prefix route for "admin" and added the authentication middleware to it as such:

```php
Router::prefix('Admin', function ($routes) {

    $loginUrl = Router::url('/admin/users/login');
    $fields = [
        'username' => 'username',
        'password' => 'password'
    ];
    
    $service = new AuthenticationService([
        'unauthenticatedRedirect' => $loginUrl,
        'queryParam' => 'redirect',
    ]);
    $service->loadAuthenticator('Authentication.Session');
    $service->loadAuthenticator('Authentication.Form', [
        'fields' => $fields,
        'loginUrl' => $loginUrl
    ]);
    $service->loadIdentifier('Authentication.Password', compact('fields'));
    
    $routes->registerMiddleware('auth', new \Authentication\Middleware\AuthenticationMiddleware($service));
    $routes->applyMiddleware('auth');
    
    $routes->connect('/', ['controller' => 'Users', 'action' => 'index']);
    $routes->fallbacks(DashedRoute::class);
});
```
Now when I go to any of the protected pages, such as localhost\v3\admin\whatever I get kicked out to localhost\admin\users\login, instead of localhost\v3\admin\users\login.

Hard coding v3 as a basedir is not an option because it makes the code not portable.

Is there a way to set this up so authentication works as expected regardless what subdirectory cakephp is installed in?

**Comment by ADmad** [comment] 2020-02-23 05:14
Are you using the latest 2.x release?  I have a similar setup as yours and don't have any issue with redirection.

**Comment by gunner1095** [comment] 2020-02-23 08:13
Yes. (Windows 10, Bitnami WAMP Stack 7.3.12-0)
```
cakephp/authentication                2.0.5                Authentication plugin for CakePHP
```
I can try reinstalling everything completely from scratch again to see if it can be replicated, but this is pretty much a vanilla install as it is.

**Comment by markstory** [comment] 2020-02-23 18:07
Does the `$loginUrl` in the provided code have the prefix applied? If not your redirects will be incorrect, as the authentication plugin doesn't handle applying prefixes.

**Comment by ADmad** [comment] 2020-02-23 18:10
URL returned `Router::url('/admin/users/login')` should contain the subdirectory/basepath.

**Comment by ndm2** [comment] 2020-02-23 19:57
I think the problem is that routes are loaded and evaluated before the router receives the request context, so it doesn't yet know about the possible base path.

https://github.com/cakephp/cakephp/blob/4.0.4/src/Routing/Middleware/RoutingMiddleware.php#L130-L132

**Comment by gunner1095** [comment] 2020-02-23 20:27
Yeah, I tried it a number of different ways and I get the same result: the basepath is missing from the url. 

Btw, if I hard code the base path into the unauthenticatedRedirect option... 
```
$routes->prefix('Admin', function ($routes) {
   ...
     $service = new AuthenticationService([
         'unauthenticatedRedirect' => '/v3/admin/users/login',
         'queryParam' => 'redirect',
     ]);
   ...
}
```
...it redirects to the correct login url, but the redirect option in the query param is still missing the base path:

```
http://localhost/v3/admin/users/login?redirect=%2Fadmin
```

**Comment by ADmad** [comment] 2020-02-24 02:19
> I think the problem is that routes are loaded and evaluated before the router receives the request context, so it doesn't yet know about the possible base path.

Aha, I do all the config for the authentication service in the `getAuthenticationService()` method, hence I don't have any issues and the router context is set by that time.

**Comment by gunner1095** [comment] 2020-02-24 02:45
>  I do all the config for the authentication service in the getAuthenticationService() method

Doesn't that mean that those authentication settings will apply to the entire application though? For my use case I will need a separate login for admins and members. The rest of the site is pretty much static and doesn't need authentication at all.

My thought was...

```php
Router::prefix('Admin', function ($routes) {
   // Authentication service with settings specific for admin scope
   $service = new AuthenticationService(...)
   $routes->registerMiddleware('auth', new AuthenticationMiddleware($service));
   $routes->applyMiddleware('auth');
}

Router::prefix('Members', function ($routes) {
   // Authentication service with settings specific for members scope
   $service = new AuthenticationService(...)
   $routes->registerMiddleware('auth', new AuthenticationMiddleware($service));
   $routes->applyMiddleware('auth');
}
```
Is there a different way of doing this?

**Comment by markstory** [comment] 2020-02-24 02:51
> Is there a different way of doing this?

If you pass the application into the AuthenticationMiddleware it will defer the creation of the `AuthenticationService` until authentication is applied which should be after routing is setup.

**Comment by gunner1095** [comment] 2020-02-24 03:12
Like this?

```php
$routes->registerMiddleware('auth', new AuthenticationMiddleware($this));
```

**Comment by markstory** [comment] 2020-02-24 22:11
Yes, as long as `$this` is the application object and implements the `AuthenticationServiceProviderInterface`.

**Comment by gunner1095** [comment] 2020-02-25 00:10
But then going back to my original use case, how can I specify different settings for each of my prefix routes?

```php
Router::prefix('Admin', function ($routes) {
   // this needs to redirect unauthenticated requests to /admin/users/login...
   $routes->registerMiddleware('auth', new AuthenticationMiddleware($this));
}

Router::prefix('Members', function ($routes) {
   // this needs to redirect unauthenticated requests to /admin/memberse/login...
   $routes->registerMiddleware('auth', new AuthenticationMiddleware($this));
}
```
Unless I misunderstand, both scopes will have the same settings from...
```php
class Application extends BaseApplication implements AuthenticationServiceProviderInterface
{
  ...

  public function getAuthenticationService(ServerRequestInterface $request): AuthenticationServiceInterface
  {
    // need different settings for each scope... 
     ...
  }
}
```
So, how to apply different authentication settings to different prefix routes?

**Comment by ndm2** [comment] 2020-02-25 01:31
You could evaluate the matched prefix, and configure the service accordingly, like:

```php
// ...

$params = $request->getAttribute('params');
switch ($params['prefix']) {
    case 'Admin':
        // apply admin config
        break;

    case 'Members':
        // apply members config
        break;
}

return $service;
```

**Comment by RobertoRoos** [comment] 2020-11-22 10:33
Just wanted to confirm the subdirectory redirect issue has been fixed.

I was having this issue with CakePHP 4.1.6 just now, but it turns out I made a typo in my composer require and I was not using the latest Authentication version. In Authentication 2.3 an application in a subdirectory is handled correctly.

**Closed** 2020-11-22 10:42 UTC
